import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import API from '../api';
import MultipleChoice from '../components/QuestionTypes/MultipleChoice';
import OpenEnded from '../components/QuestionTypes/OpenEnded';
import ImageComparison from '../components/QuestionTypes/ImageComparison';
import Conversational from '../components/QuestionTypes/Conversational';
import { v4 as uuidv4 } from 'uuid'; // For generating anonymous session ID

const PublicSurveyPage = () => {
    const { publicShareId } = useParams();
    const [survey, setSurvey] = useState(null);
    const [answers, setAnswers] = useState({});
    const [loading, setLoading] = useState(true);
    const [message, setMessage] = useState('');
    const [anonymousSessionId, setAnonymousSessionId] = useState(localStorage.getItem('anonymousSessionId') || uuidv4());

    useEffect(() => {
        // Store anonymous session ID in localStorage for persistence across refreshes
        localStorage.setItem('anonymousSessionId', anonymousSessionId);

        const fetchSurvey = async () => {
            try {
                const res = await API.get(`/public/surveys/${publicShareId}`);
                setSurvey(res.data);
                const initialAnswers = {};
                res.data.questions.forEach(q => {
                    initialAnswers[q._id] = '';
                });
                setAnswers(initialAnswers);
            } catch (err) {
                setMessage(err.response?.data?.message || 'Failed to load public survey.');
            } finally {
                setLoading(false);
            }
        };
        fetchSurvey();
    }, [publicShareId, anonymousSessionId]);

    const handleAnswerChange = (questionId, value) => {
        setAnswers(prev => ({ ...prev, [questionId]: value }));
    };

    const handleSubmit = async () => {
        setMessage('');
        setLoading(true);
        try {
            const formattedAnswers = survey.questions.map(q => ({
                questionId: q._id,
                questionType: q.questionType,
                value: answers[q._id]
            }));

            const res = await API.post(`/public/surveys/${publicShareId}/submit`, {
                answers: formattedAnswers,
                anonymousSessionId // Send the anonymous session ID
            });
            setMessage(res.data.message + ` (Your response was anonymous)`);
            setAnonymousSessionId(res.data.anonymousSessionId); // Update if a new one was generated by backend
            // For public surveys, no redirect, just show success message
        } catch (err) {
            setMessage(err.response?.data?.message || 'Error submitting survey.');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    if (loading) return <div className="flex justify-center items-center min-h-screen text-xl">Loading survey...</div>;
    if (message && !survey) return <div className="flex justify-center items-center min-h-screen text-xl text-red-500">{message}</div>;
    if (!survey) return <div className="flex justify-center items-center min-h-screen text-xl">Survey not found.</div>;

    return (
        <div className="min-h-screen bg-gray-100 p-8">
            <div className="max-w-3xl mx-auto bg-white rounded-lg shadow-xl p-8">
                <h1 className="text-3xl font-bold text-gray-800 mb-4 text-center">{survey.title}</h1>
                <p className="text-gray-600 mb-6 text-center">{survey.description}</p>
                <p className="text-orange-600 text-center font-semibold mb-6">
                    This is an anonymous survey. Your responses will not be linked to your personal identity.
                </p>
                {message && <p className="mb-4 text-center text-green-600 font-semibold">{message}</p>}

                {survey.questions.map((question, index) => (
                    <div key={question._id} className="mb-8 p-6 border border-gray-200 rounded-lg bg-gray-50 shadow-sm">
                        <h2 className="text-xl font-semibold text-gray-700 mb-4">
                            {index + 1}. {question.questionText}
                        </h2>
                        {question.questionType === 'multiple-choice' && (
                            <MultipleChoice
                                question={question}
                                answer={answers[question._id]}
                                setAnswer={(val) => handleAnswerChange(question._id, val)}
                            />
                        )}
                        {question.questionType === 'open-ended' && (
                            <OpenEnded
                                question={question}
                                answer={answers[question._id]}
                                setAnswer={(val) => handleAnswerChange(question._id, val)}
                            />
                        )}
                        {question.questionType === 'image-comparison' && (
                            <ImageComparison
                                question={question}
                                answer={answers[question._id]}
                                setAnswer={(val) => handleAnswerChange(question._id, val)}
                            />
                        )}
                        {question.questionType === 'conversational' && (
                            <Conversational
                                question={question}
                                surveyId={survey._id}
                                userId={null} // No logged-in user for public surveys
                                anonymousSessionId={anonymousSessionId} // Pass anonymous session ID
                            />
                        )}
                    </div>
                ))}

                <div className="mt-8 flex justify-center">
                    <button
                        onClick={handleSubmit}
                        className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-lg shadow-lg transition-colors duration-200"
                        disabled={loading}
                    >
                        {loading ? 'Submitting...' : 'Submit Anonymous Response'}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default PublicSurveyPage;